### ISSUE TITLE
Template issues

### ISSUE THREAD

**Issue by itwasmattgregg** [bencodezen/obsidian-starter-kit#2]
The template syntax of `tp_date` etc. aren't working for me. It appears obsidian changed it to {{date}} and {{title}} unless you're using some plugin.

**Comment by taismassaro** [comment]
he uses the [templater](https://github.com/SilentVoid13/Templater) plugin, but the syntax also changed for that. he was updating the plugin live on twitch today. you can see the newest syntax in the linked repo! :)

**Comment by itwasmattgregg** [comment]
Thanks for the link :)
